package de.medizininformatikinitiative.medgraph.searchengine.matcher.model;

/**
 * Interface for classes carrying additional information about a match generated by an
 * {@link de.medizininformatikinitiative.medgraph.searchengine.matcher.IMatcher}.
 *
 * @author Markus Budeus
 */
public interface MatchInfo {
}
