package de.medizininformatikinitiative.medgraph.fhirexporter.exporter_old;

import de.medizininformatikinitiative.medgraph.fhirexporter.fhir.FhirResource;
import org.neo4j.driver.Result;
import org.neo4j.driver.Session;

import java.util.stream.Stream;

/**
 * Class which exports data from the Neo4j Graph database.
 *
 * @param <T> the type of exported objects
 * @author Markus Budeus
 */
public abstract class Neo4jExporter<T extends FhirResource> {

	public static final String META_SOURCE = "https://www.mmi.de/mmi-pharmindex/mmi-pharmindex-daten";

	protected final Session session;

	public Neo4jExporter(Session session) {
		this.session = session;
	}

	public abstract Stream<T> exportObjects();

	public int countObjects() {
		Result result = session.run(createObjectCountQuery());

		if (!result.hasNext()) return 0;
		return result.next().get(0).asInt();
	}

	/**
	 * Returns a Cypher query which counts the amount of objects which would be generated by this exporter. The query
	 * must produce exactly one result, which is the count.
	 */
	protected abstract String createObjectCountQuery();

}
