package de.medizininformatikinitiative.medgraph.searchengine.model.matchingobject;

import de.medizininformatikinitiative.medgraph.searchengine.model.identifiable.Matchable;
import de.medizininformatikinitiative.medgraph.searchengine.model.pipelinestep.Transformation;

/**
 * A {@link MatchingObject} to which a transformation has been applied. This instance references the
 * {@link MatchingObject} from which it originated during the transformation as well as the corresponding
 * {@link Transformation}.
 *
 * @param <S> the type of {@link MatchingObject} which was transformed
 * @param <T> the type of this object's {@link Matchable}
 * @author Markus Budeus
 */
public class TransformedObject<S extends Matchable, T extends Matchable> extends MatchingObject<T> {

	private final MatchingObject<S> source;
	private final Transformation transformation;

	/**
	 * Creates a new {@link TransformedObject}.
	 * @param object the {@link Matchable} managed by this instance
	 * @param source the {@link MatchingObject} from which this instance was generated by the transformation
	 * @param transformation the {@link Transformation} which generated this instance
	 */
	public TransformedObject(T object, MatchingObject<S> source, Transformation transformation) {
		super(object);
		this.source = source;
		this.transformation = transformation;
	}

	/**
	 * Returns the object this instance originated from via the transformation.
	 */
	public MatchingObject<S> getSourceObject() {
		return source;
	}

	/**
	 * Returns the transformation this instance originated from.
	 */
	public Transformation getTransformation() {
		return transformation;
	}

}
